PUT http://localhost:3003/api/blogs/6883e4c18101d96be8a3c584
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikx1dWtfVW5nZXIiLCJpZCI6IjY4ODNlNDliODEwMWQ5NmJlOGEzYzU4MCIsImlhdCI6MTc1MzczODk1MH0.BQeHoSUPFw5gfCRyzqrD5lAMWkJDq377uwKxuJGO5S8


{
  "title": "horomonons",
  "author": "me",
  "url": "blank",
  "likes": 13,
  "user": "6883e49b8101d96be8a3c580"
}